# Generated by Django 5.1.4 on 2025-09-18 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_received', 'Pagamento Recebido'), ('payment_overdue', 'Pagamento Vencido'), ('payment_reminder', 'Lembrete de Pagamento'), ('subscription_expiring', 'Assinatura Expirando')], max_length=30, verbose_name='Tipo de Notificação')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('sent_via', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20, verbose_name='Enviado via')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Notificação de Pagamento',
                'verbose_name_plural': 'Notificações de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Relatório Mensal'), ('quarterly', 'Relatório Trimestral'), ('annual', 'Relatório Anual'), ('custom', 'Relatório Personalizado')], max_length=20, verbose_name='Tipo de Relatório')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Receita Total')),
                ('total_payments', models.PositiveIntegerField(default=0, verbose_name='Total de Pagamentos')),
                ('paid_payments', models.PositiveIntegerField(default=0, verbose_name='Pagamentos Realizados')),
                ('pending_payments', models.PositiveIntegerField(default=0, verbose_name='Pagamentos Pendentes')),
                ('overdue_payments', models.PositiveIntegerField(default=0, verbose_name='Pagamentos Vencidos')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Arquivo do Relatório')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Relatório de Pagamento',
                'verbose_name_plural': 'Relatórios de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIXPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix_payment_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID do Pagamento PIX')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='ID Externo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('pix_key', models.CharField(blank=True, max_length=100, verbose_name='Chave PIX')),
                ('pix_qr_code', models.ImageField(blank=True, null=True, upload_to='pix/qr_codes/', verbose_name='QR Code PIX')),
                ('pix_copy_paste', models.TextField(blank=True, verbose_name='Código PIX Copia e Cola')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pix_payment', to='students.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento PIX',
                'verbose_name_plural': 'Pagamentos PIX',
                'ordering': ['-created_at'],
            },
        ),
    ]
