# Generated by Django 5.1.4 on 2025-09-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='Google Maps (embed/view URL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tawkto_property_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tawk.to Property ID'),
        ),
    ]
