# Generated by Django 5.1.4 on 2025-09-30 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_google_maps_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/categories/', verbose_name='Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Descrição Curta')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('out_of_stock', 'Esgotado'), ('discontinued', 'Descontinuado')], default='draft', max_length=20, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Comparação')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Controlar Estoque')),
                ('main_image', models.ImageField(upload_to='shop/products/', verbose_name='Imagem Principal')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Imagens Adicionais')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=50, verbose_name='Dimensões (LxAxP cm)')),
                ('colors', models.JSONField(blank=True, default=list, verbose_name='Cores Disponíveis')),
                ('sizes', models.JSONField(blank=True, default=list, verbose_name='Tamanhos Disponíveis')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Mais Vendido')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.productcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Estrela'), (2, '2 Estrelas'), (3, '3 Estrelas'), (4, '4 Estrelas'), (5, '5 Estrelas')], verbose_name='Avaliação')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('comment', models.TextField(verbose_name='Comentário')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Avaliação de Produto',
                'verbose_name_plural': 'Avaliações de Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
