# Generated by Django 5.1.4 on 2025-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatmessage_chattemplate_customerloyalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='whatsapp_url',
            field=models.TextField(blank=True, help_text='URL para enviar a mensagem via WhatsApp', verbose_name='URL WhatsApp'),
        ),
    ]
